In [27]:
#Importamos librerias

import pandas as pd 
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [28]:
data = pd.read_csv("servicio_clientes.csv")

In [29]:
#Visualizacion:

data.head()

   edad  meses_cliente  ...  contrato_anual  deserto
0    22              3  ...               0        1
1    45             36  ...               1        0
2    31              8  ...               0        1
3    52             48  ...               1        0
4    28              6  ...               0        1

[5 rows x 7 columns]

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   edad             24 non-null     int64
 1   meses_cliente    24 non-null     int64
 2   soporte_mensual  24 non-null     int64
 3   retrasos_pago    24 non-null     int64
 4   uso_mensual_gb   24 non-null     int64
 5   contrato_anual   24 non-null     int64
 6   deserto          24 non-null     int64
dtypes: int64(7)
memory usage: 1.4 KB

In [31]:
data.describe()

            edad  meses_cliente  ...  contrato_anual    deserto
count  24.000000      24.000000  ...       24.000000  24.000000
mean   38.833333      24.333333  ...        0.500000   0.500000
std    11.102944      19.322586  ...        0.510754   0.510754
min    22.000000       3.000000  ...        0.000000   0.000000
25%    29.750000       6.750000  ...        0.000000   0.000000
50%    38.000000      19.500000  ...        0.500000   0.500000
75%    46.500000      39.000000  ...        1.000000   1.000000
max    60.000000      60.000000  ...        1.000000   1.000000

[8 rows x 7 columns]

In [32]:
#Usamos columns para ver los labels

data.columns

Index(['edad', 'meses_cliente', 'soporte_mensual', 'retrasos_pago',
       'uso_mensual_gb', 'contrato_anual', 'deserto'],
      dtype='object')

In [33]:
#Definimos X y Y 

X = data[["edad","meses_cliente","soporte_mensual","retrasos_pago","uso_mensual_gb","contrato_anual"]]
Y = data["deserto"]

In [34]:
#Creamos el modelo

model = LogisticRegression(max_iter=1000)
#entrenamos al modelo
cross = cross_val_score(model,X,Y, cv=5)

In [35]:
mean = np.mean(cross)

In [38]:
print(cross)
print("El promedio de el modelo es de:",mean)

[1. 1. 1. 1. 1.]
El promedio de el modelo es de: 1.0