In [1]:
#Importamos las librerias 

import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
#Cargamos el dataset 

data = pd.read_csv("Prediccion_de_precios_de_automoviles.csv")

In [3]:
#Visualizamos la informacion

data.head()

,id,marca,modelo,año,kilometraje_km,cilindrada_cc,combustible,transmision,puertas,propietarios,precio_usd
0,1,Toyota,Corolla,2020,35000,1800,Gasolina,Automatica,4,1,18500
1,2,Honda,Civic,2019,42000,2000,Gasolina,Automatica,4,1,19200
2,3,Ford,Focus,2018,55000,1600,Gasolina,Manual,4,2,13500
3,4,Chevrolet,Spark,2021,18000,1200,Gasolina,Manual,4,1,9800
4,5,Nissan,Sentra,2020,30000,1800,Gasolina,CVT,4,1,16500

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              50 non-null     int64
 1   marca           50 non-null     object
 2   modelo          50 non-null     object
 3   año             50 non-null     int64
 4   kilometraje_km  50 non-null     int64
 5   cilindrada_cc   50 non-null     int64
 6   combustible     50 non-null     object
 7   transmision     50 non-null     object
 8   puertas         50 non-null     int64
 9   propietarios    50 non-null     int64
 10  precio_usd      50 non-null     int64
dtypes: int64(7), object(4)
memory usage: 4.4+ KB

In [5]:
data.describe()

,id,año,kilometraje_km,cilindrada_cc,puertas,propietarios,precio_usd
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,2019.560000,40280.000000,1828.000000,3.960000,1.400000,22800.000000
std,14.57738,1.296148,18639.479716,822.400667,0.282843,0.571429,9687.125898
min,1.00000,2016.000000,12000.000000,0.000000,2.000000,1.000000,8900.000000
25%,13.25000,2019.000000,27250.000000,1500.000000,4.000000,1.000000,15500.000000
50%,25.50000,2020.000000,37000.000000,1800.000000,4.000000,1.000000,21400.000000
75%,37.75000,2020.000000,49750.000000,2000.000000,4.000000,2.000000,28250.000000
max,50.00000,2022.000000,92000.000000,5000.000000,4.000000,3.000000,47500.000000

In [6]:
#Definimos X y Y 

X = data["marca","año","kilometraje","cilindrada_cc","transmision","propietarios"]
y = data["precio_usd"]

KeyError: ('marca', 'año', 'kilometraje', 'cilindrada_cc', 'transmision', 'propietarios')

In [ ]:
#Separamos entrenamiento y evaluacion 

x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
#Creamos el modelo 

model = RandomForestRegressor(
    n_estimators=100,
    max_features=5,
    random_state=42
)

In [ ]:
#Evaluamos 

pre = model.predict(x_test)