In [189]:
#Importamos las librerias

import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [190]:
#Cargamos el dataset 

data = pd.read_csv("Ventasdeunatienda.csv")

In [191]:
#Visualizamos 

data.head()

,id,dia_semana,publicidad,clientes,precio_promedio,descuento,stock,ventas
0,1,Lunes,120,45,18.5,5,80,820
1,2,Martes,80,38,19.0,0,75,710
2,3,Miercoles,150,52,17.5,10,90,980
3,4,Jueves,100,47,18.0,5,85,870
4,5,Viernes,200,68,19.5,15,100,1350

In [192]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50 non-null     int64
 1   dia_semana       50 non-null     object
 2   publicidad       50 non-null     int64
 3   clientes         50 non-null     int64
 4   precio_promedio  50 non-null     float64
 5   descuento        50 non-null     int64
 6   stock            50 non-null     int64
 7   ventas           50 non-null     int64
dtypes: float64(1), int64(6), object(1)
memory usage: 3.3+ KB

In [193]:
data.describe()

,id,publicidad,clientes,precio_promedio,descuento,stock,ventas
count,50.00000,50.000000,50.00000,50.0000,50.000000,50.000000,50.000000
mean,25.50000,185.700000,63.76000,19.1600,9.200000,103.880000,1258.000000
std,14.57738,71.414356,20.09118,1.0174,6.256425,25.088936,488.675845
min,1.00000,80.000000,35.00000,17.5000,0.000000,68.000000,650.000000
25%,13.25000,130.000000,47.25000,18.5000,5.000000,85.000000,855.000000
50%,25.50000,172.500000,58.50000,19.0000,10.000000,99.000000,1090.000000
75%,37.75000,237.500000,78.75000,20.0000,15.000000,120.000000,1610.000000
max,50.00000,350.000000,110.00000,21.5000,20.000000,165.000000,2420.000000

In [194]:
#Usamos columns

data.columns

Index(['id', 'dia_semana', 'publicidad', 'clientes', 'precio_promedio',
       'descuento', 'stock', 'ventas'],
      dtype='object')

In [195]:
#Convertir el día de la semana a variables numéricas
data = pd.get_dummies(data, columns=["dia_semana"], drop_first=True)

In [196]:
#Separar variables predictoras (X) y variable objetivo (y)
X = data.drop(columns=["id", "ventas"])
y = data["ventas"]

In [197]:
#Separamos entrenamiento y prueba

x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [198]:
#Creamos el modelo y lo entrenamos

model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [199]:
#Lo evaluamos 

pre = model.predict(x_test)

In [200]:
data.head()

,id,publicidad,clientes,precio_promedio,descuento,stock,ventas,dia_semana_Jueves,dia_semana_Lunes,dia_semana_Martes,dia_semana_Miercoles,dia_semana_Sabado,dia_semana_Viernes
0,1,120,45,18.5,5,80,820,False,True,False,False,False,False
1,2,80,38,19.0,0,75,710,False,False,True,False,False,False
2,3,150,52,17.5,10,90,980,False,False,False,True,False,False
3,4,100,47,18.0,5,85,870,True,False,False,False,False,False
4,5,200,68,19.5,15,100,1350,False,False,False,False,False,True

In [201]:
#Nueva prediccion 

prediccion = pd.DataFrame({ 
    "publicidad": [110],
    "clientes": [50],
    "precio_promedio": [19.0],
    "descuento": [5],
    "stock": [80],
    "dia_semana_Jueves": [0],
    "dia_semana_Lunes": [1],
    "dia_semana_Martes": [0],
    "dia_semana_Miercoles": [0],
    "dia_semana_Sabado": [1],
    "dia_semana_Viernes": [1]
})

In [202]:
nueva_prediccion = model.predict(prediccion)

In [203]:
print(nueva_prediccion)

[1309.25761947]

In [206]:
model.score(x_train,y_train)

0.9988747776900089